API_KEY = '4e9dfc448d344e74aeb121352241102'
BASE_URL = 'https://api.weatherapi.com/v1'
HISTORY_URL = '/history.json'
SEARCH_URL = '/search.json'
DAYS_AGO = 3
KEY = 'key'

FORECAST = 'forecast'
FORECASTDAY = 'forecastday'
DATE = 'date'
DAY = 'day'
HOUR = 'hour'
AVERAGE_C = 'avgtemp_c'
MIN_C = 'mintemp_c'
MAX_C = 'maxtemp_c'
TEMP_C = 'temp_c'
LOCATION = 'location'
LAT = 'lat'
LON = 'lon'
ASTRO = 'astro'
SUNRISE = 'sunrise'

CITY_PARAM = 'q'
DATE_PARAM = 'dt'
